# Generated by Django 4.2 on 2023-07-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='Default Destination', max_length=100),
        ),
    ]
